#!/bin/sh
#
# EasyTether script to open a connection by using two steps.
# This script is step 1, which opens a new connection.
#
# Syntax:
#
#     easytether-connect-1 [device]
#
# ## Device details
#
# To enumerate connection devices, e.g. serial numbers:
#
#    easytether enumerate
#
# ## Customization
#
# If you are using gnome, and you want this script to automatically
# open a terminal, then you can edit this script such as:
#
#     gnome-terminal -x easytether connect
#
# ## About
#
#   * Program: easytether-connect-start
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
#   * Created: 2010-11-04
#   * Updated: 2016-02-90
#   * License: GPL
##
set -euf
easytether connect "$@"
